site_name: Openveo <%= Plugin %>
theme: readthedocs
site_dir: site/version
markdown_extensions:
  - fenced_code
  - tables
nav:
- 'INTRODUCTION': 'index.md'
- 'DEVELOPERS':
  - 'Installation': 'developers/installation.md'
  - 'CSS / SASS / JS compilation': 'developers/compilation.md'
  - 'Unit tests': 'developers/unit-tests.md'
  - 'End to end tests': 'developers/end-to-end-tests.md'
